# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Stowarzyszenie "Dzieci Funduszu"'
tagline:          'Stowarzyszenie "Dzieci Funduszu"'
description:      'Stowarzyszenie Przyjaciół i Absolwentów Krajowego Funduszu na&nbsp;rzecz Dzieci "Dzieci Funduszu"'
url:              http://absolwenci-funduszu.org
baseurl:          /

author:
  name:           'Błażej Osiński'

paginate:         5
